import React from "react";
import { type LucideProps } from "lucide-react";
import {
  Landmark,
  Wallet,
  Plus,
  PlusSquare,
  PlusCircle,
  ShoppingCart,
  ArrowRight,
  ArrowUp,
  Undo2,
  ScanBarcode,
  Zap,
  Calendar,
  Phone,
  Check,
  CheckCircle2,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ClipboardList,
  X,
  CreditCard,
  Trash2,
  FileText,
  Building2,
  CheckCheck,
  Download,
  Pencil,
  FileEdit,
  AlertCircle,
  Factory,
  Scale,
  ShieldCheck,
  Boxes,
  Package,
  Pill,
  Truck,
  LogIn,
  LogOut,
  Mail,
  Stethoscope,
  BarChart3,
  Bell,
  Banknote,
  User,
  UserPlus,
  Store,
  Printer,
  PackageX,
  Loader2,
  Receipt,
  RefreshCw,
  Save,
  Clock,
  Search,
  SearchX,
  Send,
  ShoppingBag,
  Gauge,
  Star,
  TrendingUp,
  SlidersHorizontal,
  BadgeCheck,
  AlertTriangle,
  HelpCircle,
  Activity,
  Shield,
  Info,
  DollarSign
} from "lucide-react";
import { cn } from "@/lib/utils";

export const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  activity: Activity,
  add: Plus,
  add_box: PlusSquare,
  add_circle: PlusCircle,
  add_shopping_cart: ShoppingCart,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assignment_return: Undo2,
  barcode_scanner: ScanBarcode,
  bell: Bell,
  bolt: Zap,
  calendar_today: Calendar,
  call: Phone,
  check: Check,
  check_circle: CheckCircle2,
  chevron_down: ChevronDown,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  clinical_notes: ClipboardList,
  close: X,
  credit_card: CreditCard,
  delete: Trash2,
  delete_sweep: Trash2,
  description: FileText,
  dollar_sign: DollarSign,
  domain: Building2,
  domain_add: Building2,
  done: Check,
  done_all: CheckCheck,
  download: Download,
  edit: Pencil,
  edit_note: FileEdit,
  error: AlertCircle,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  factory: Factory,
  file_download: Download,
  gavel: Scale,
  health_and_safety: ShieldCheck,
  help: HelpCircle,
  info: Info,
  inventory: Boxes,
  inventory_2: Package,
  local_pharmacy: Pill,
  local_shipping: Truck,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  medical_services: Stethoscope,
  monitoring: BarChart3,
  notifications: Bell,
  payments: Banknote,
  person: User,
  person_add: UserPlus,
  pill: Pill,
  point_of_sale: Store,
  print: Printer,
  production_quantity_limits: PackageX,
  progress_activity: Loader2,
  receipt: Receipt,
  receipt_long: Receipt,
  refresh: RefreshCw,
  save: Save,
  scale: Scale,
  schedule: Clock,
  search: Search,
  search_off: SearchX,
  send: Send,
  shield: Shield,
  shopping_bag: ShoppingBag,
  speed: Gauge,
  star: Star,
  stethoscope: Stethoscope,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  user: User,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  warning: AlertTriangle,
};

export interface IconProps extends Omit<LucideProps, "ref"> {
  name: string;
  className?: string;
  size?: number | string;
  title?: string;
}

export function Icon({ name, className, size = "1.15em", ...props }: IconProps) {
  const IconComponent = iconMap[name] || HelpCircle;
  return (
    <IconComponent
      className={cn("inline-block shrink-0 align-middle", className)}
      size={size}
      {...props}
    />
  );
}
